# 构建 docker 镜像并推到 docker hub

name: Build docker image
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - name: Get Version
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF:10}
      - name: Build the tagged Docker image
        run: docker build . --file Dockerfile --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{steps.vars.outputs.tag}}
      - name: Push the tagged Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ github.repository }}:${{steps.vars.outputs.tag}}
